language: ruby
sudo: false
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  - git config --global user.name "TravisCI"
  - git config --global user.email "noreply@example.com"
  - sudo apt-get install wkhtmltopdf
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false

matrix:
  include:
    - rvm: 2.3
      env: "CHECK=spec"

    - rvm: 2.5
      env: "CHECK=spec"

    - rvm: 2.6
      env: "CHECK=spec"
